### ISSUE TITLE
Unable to disable "Displayed cover follows playing track"

### ISSUE THREAD

**Issue by bitvan** [Chronial/foo_chronflow#3]
Hi, I'm using the official version of Foobar2000 v1.4.4 on Windows 7 Ultimate (64bit).

For unknown reason, the checkbox and text for "Displayed cover follows playing track, after seconds of inactivity" is always greyed out (checkbox is ticked on default and not changable). I tried to toggle other options, but it stays grey. Is this intended or a possible bug? How do I uncheck the checkbox?

The seconds count is working, but I don't want the displayed cover to move by itself.

Any help would be greatly appreciated.

**Comment by Chronial** [comment]
Thx for reporting, that's a bug. It will be fixed in the next release. Until then you can just enter a bunch of 9s into the delay field, so the delay won't actually be hit.

**Comment by bitvan** [comment]
Thanks for confirming it's a bug. I tried to add 9s but the highest I can go is "999" (beyond that it can't be saved, 999 sec is about 16min).

If you have any date in mind for the next release, that would be nice to know. (no hurry tho)

**Comment by Chronial** [comment]
No date, but if I manage to find the source of #2 and fix it, that will probably worth a release

**Comment by Chronial** [comment]
Release is out: https://github.com/Chronial/foo_chronflow/releases/tag/v0.5.1

**Comment by bitvan** [comment]
Thanks a lot for the new release. I've been waiting to see it.
